"""add_file_metadata_table

Revision ID: 86e6950aa32c
Revises: 0012e2f3605a
Create Date: 2025-06-02 10:40:45.678865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '86e6950aa32c'
down_revision: Union[str, None] = '0012e2f3605a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file_metadata', 'storage_path',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1024),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.create_index(op.f('ix_file_metadata_storage_path'), 'file_metadata', ['storage_path'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_metadata_storage_path'), table_name='file_metadata')
    op.alter_column('file_metadata', 'storage_path',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1024),
               existing_nullable=False)
    # ### end Alembic commands ###
